# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = Fytoplakton.o main.o Mhplakton.o Organism.o Plakton.o Zwoplakton.o $(RES)
LINKOBJ  = Fytoplakton.o main.o Mhplakton.o Organism.o Plakton.o Zwoplakton.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = Project1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Project1.exe" $(LIBS)

Fytoplakton.o: Fytoplakton.cpp
	$(CPP) -c Fytoplakton.cpp -o Fytoplakton.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Mhplakton.o: Mhplakton.cpp
	$(CPP) -c Mhplakton.cpp -o Mhplakton.o $(CXXFLAGS)

Organism.o: Organism.cpp
	$(CPP) -c Organism.cpp -o Organism.o $(CXXFLAGS)

Plakton.o: Plakton.cpp
	$(CPP) -c Plakton.cpp -o Plakton.o $(CXXFLAGS)

Zwoplakton.o: Zwoplakton.cpp
	$(CPP) -c Zwoplakton.cpp -o Zwoplakton.o $(CXXFLAGS)
